baseURL = "https://questra.digital"
languageCode = "en-us"
title = "Questra Digital"
theme = "profile"

[params]
  description = ""
  tagline = "Transforming digitization through open-sourced, collaborative and self-sustained models"
  email = "jawad@questra.digital"
  phone = "+92 321 4189015"
  address = ""
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Mission"
    url = "/#mission"
    weight = 2
  [[menu.main]]
    name = "Vision"
    url = "/#vision"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url = "/#projects"
    weight = 4
  [[menu.main]]
    name = "Labs & Brands"
    url = "/#labs"
    weight = 5
  [[menu.main]]
    name = "Gigs"
    url = "/#gigs"
    weight = 6
  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 7

[[menu.main]]
name = "Product"
url = "/product/"
weight = 8

[[menu.main]]
name = "Solution"
url = "/solution/"
weight = 9

[[menu.main]]
name = "Course"
url = "/course/"
weight = 10

[[menu.main]]
name = "Freelancer"
url = "/freelancer/"
weight = 11
